// remote-react/src/components/Button.tsx
import { useState, useEffect } from 'react';
import { store } from 'host_app/store';

export const Button = () => {
  const [count, setCount] = useState(store.get().count);

  useEffect(() => {
    const cleanup = store.subscribe((state: { count: number }) => {
      setCount(state.count);
    });
    return cleanup;
  }, []);

  return (
    <button 
      onClick={() => store.set({ count: count + 1 })}
      style={{ backgroundColor: 'blue', color: 'white', padding: '10px 20px', border: 'none', borderRadius: '5px' }}
    >
      Remote React Button (Count: {count})
    </button>
  );
};

export default Button;

// remote-vue/src/components/Button.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
// @ts-ignore
import { store } from "host_app/store";

const count = ref(0);
let cleanup: () => void;

const increment = () => {
  store.set({ count: count.value + 1 });
};

onMounted(() => {
  count.value = store.get().count;
  cleanup = store.subscribe((state: { count: number }) => {
    console.log("[RemoteVue] Count updated:", state.count);
    count.value = state.count;
  });
});

onUnmounted(() => {
  if (cleanup) cleanup();
});
</script>

<template>
  <button class="remote-vue-button" @click="increment">
    Remote Vue Button (Count: {{ count }})
  </button>
</template>

<style scoped>
.remote-vue-button {
  background-color: #42b883;
  color: white;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
}
</style>
